services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=disappear_secret
      - POSTGRES_DB=freedom_db
    ports:
      - "5432:5432"
    # This automatically updates Alpine, installs openssl, creates the keys, locks them down, and starts Postgres
    entrypoint: >
      sh -c "
      apk add --no-cache openssl &&
      if [ ! -f /var/lib/postgresql/data/server.key ]; then
        openssl req -new -x509 -days 365 -nodes -text -out /var/lib/postgresql/data/server.crt -keyout /var/lib/postgresql/data/server.key -subj '/CN=db' &&
        chmod 600 /var/lib/postgresql/data/server.key &&
        chown postgres:postgres /var/lib/postgresql/data/server.key
      fi &&
      exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/data/server.crt -c ssl_key_file=/var/lib/postgresql/data/server.key
      "

  backend:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/logs:/app/backend/logs
    environment:
      - DATABASE_URL=postgresql://admin:disappear_secret@db:5432/freedom_db
      - PGSSLMODE=allow
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MARQETA_BASE_URL=${MARQETA_BASE_URL}
      - MARQETA_USERNAME=${MARQETA_USERNAME}
      - MARQETA_PASSWORD=${MARQETA_PASSWORD}
      - MARQETA_WEBHOOK_SECRET=${MARQETA_WEBHOOK_SECRET}
      - MARQETA_CARD_PRODUCT_TOKEN=${MARQETA_CARD_PRODUCT_TOKEN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_API_KEY_SID=${TWILIO_API_KEY_SID}
      - TWILIO_API_KEY_SECRET=${TWILIO_API_KEY_SECRET}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true