default_platform(:ios)

platform :ios do
  desc "Build and Upload to Apple TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "XV7G933QV7",
      issuer_id: "d69c5bad-fd13-40bc-a06d-9b36c324e226",
      key_content: ENV["APPLE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      skip_profile_detection: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: {}
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
